"""Remove ProjectConfig

Revision ID: 35da80a6d570
Revises: 28ad0f531995
Create Date: 2026-01-29 15:43:58.306900

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35da80a6d570"
down_revision: str | Sequence[str] | None = "28ad0f531995"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("camera_configs")
    op.drop_table("project_configs")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_configs",
        sa.Column("project_id", sa.TEXT(), nullable=False),
        sa.Column("id", sa.TEXT(), nullable=False),
        sa.Column("fps", sa.INTEGER(), nullable=False),
        sa.Column("robot_type", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "camera_configs",
        sa.Column("project_config_id", sa.TEXT(), nullable=False),
        sa.Column("id", sa.TEXT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("fingerprint", sa.VARCHAR(length=255), nullable=False),
        sa.Column("driver", sa.VARCHAR(length=255), nullable=False),
        sa.Column("width", sa.INTEGER(), nullable=False),
        sa.Column("height", sa.INTEGER(), nullable=False),
        sa.Column("fps", sa.INTEGER(), nullable=False),
        sa.Column("use_depth", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["project_config_id"], ["project_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
